env:
  browser: true
  es2021: true

extends:
  - plugin:react/recommended
  - airbnb

parser: "@babel/eslint-parser"

parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-env"
      - "@babel/preset-react"
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true

plugins:
  - react
  - import
  - react-hooks

rules:
  import/prefer-default-export: "off"
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".js"
        - ".jsx"
  no-console: 2
  no-param-reassign: 0
  react/jsx-props-no-spreading: "off"
  react-hooks/rules-of-hooks: "error"
