vich_uploader:
    metadata:
        type: attribute
    db_driver: orm
    mappings:
       upload_product_file:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_remove: false
           delete_on_update: false
